server:
  port: 8080

spring:
  application:
    name: url-shortener-be
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signer-key: ZpVU2+KjVQEFSU6NgV9+2SRzhT5YuIsXMDgTbDcrf3Y7O+W/bYzhDwVzZSOviQwdnzGMK91zo6tAsoS+px3lkJluXeMLr0MnbhWAx7KelaI=
  expiration-time: 120 #second
  refresh_time: 12000 #second

url:
  length: 6 #characters
  expiration-time: 7 #days

api:
  prefix: /api
