server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: url-shortener-be

  datasource:
    username: root
    password: root
    url: "jdbc:mysql://localhost:3306/url"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signer-key: ZpVU2+KjVQEFSU6NgV9+2SRzhT5YuIsXMDgTbDcrf3Y7O+W/bYzhDwVzZSOviQwdnzGMK91zo6tAsoS+px3lkJluXeMLr0MnbhWAx7KelaI=
